// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.15985
//    <NameSpace>Contoso.RegiX.ReferenceAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace DAEU.RegiX.SampleAdapter
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.Runtime.Serialization;


    /// <summary>
    /// Справка за примерни данни и тестване  по идентификатор и период - резултат
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.24199")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://egov.bg/RegiX/Sample/ExampleResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace= "http://egov.bg/RegiX/Sample/ExampleResponse", IsNullable=false)]
    [System.ComponentModel.DescriptionAttribute("Примерна операция - резултат")]
    public partial class ExampleResponse {
        
        private string stringDataField;

        private string stringDataField2;

        private int intDataField;
        
        private bool intDataFieldSpecified;
        
        /// <summary>
        /// ExampleResponse class constructor
        /// </summary>
        public ExampleResponse() {
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Поле от тип низ")]
        public string StringData {
            get {
                return this.stringDataField;
            }
            set {
                this.stringDataField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.ComponentModel.DescriptionAttribute("Поле от тип низ")]
        public string StringData2
        {
            get
            {
                return this.stringDataField2;
            }
            set
            {
                this.stringDataField2 = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Поле от числов тип")]
        public int IntData {
            get {
                return this.intDataField;
            }
            set {
                this.intDataField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IntDataSpecified {
            get {
                return this.intDataFieldSpecified;
            }
            set {
                this.intDataFieldSpecified = value;
            }
        }
    }
}
